[tool.poetry]
name = "wandbot"
version = "0.1.0"
description = "A Q&A bot for Weights & Biases documnetation"
authors = ["parambharat <bharat.ramanathan@wandb.com>"]
license = "LICENSE"
readme = "README.md"
homepage = "https://github.com/wandb/wandbot"
repository = "https://github.com/wandb/wandbot"
include = ["src/**/*", "LICENSE", "README.md"]

[tool.poetry.dependencies]
python = ">=3.10.0,<3.11"
numpy = "^1.24.2"
wandb = "^0.14.0"
langchain = "^0.0.144"
faiss-cpu = "^1.7.3"
openai = "^0.27.2"
tiktoken = "^0.3.3"
pandas = "^1.5.3"
unstructured = "^0.5.8"
replit = { version = "^3.2.4", optional = true }
Flask = { version = "^2.2.0", optional = true }
urllib3 = { version = "^1.26.12", optional = true }
slack-bolt = { version = "^1.16.1", optional = true }
slack-sdk = { version = "^3.12.0", optional = true }
discord = { version = "^2.2.2", optional = true }
fastapi = { extras = ["all"], version = "^0.95.0", optional = true }
uvicorn = { version = "^0.21.1", optional = true }
python-dotenv = "^1.0.0"
cffi = "^1.15.1"

[tool.poetry.dev-dependencies]
debugpy = "^1.6.2"
replit-python-lsp-server = { extras = ["yapf", "rope", "pyflakes"], version = "^1.5.9" }

[tool.poetry.extras]
slack = ["slack-bolt", "slack-sdk"]
replit = ["replit", "Flask", "urllib3"]
discord = ["discord"]
api = ["fastapi", "uvicorn", ]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"